name: CI
on:
  push:
    branches: [main]
jobs:
  lv1-koopa:
    runs-on: ubuntu-latest
    container:
      image: xecades/compiler-dev
    steps:
      - uses: actions/checkout@v4

      - name: Get rustc version
        run: echo "rustc-version=$(rustc --version)" >> "${GITHUB_OUTPUT}"
        id: get-version

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.get-version.outputs.rustc-version }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Level 1 test
        run: |
          autotest -w ${GITHUB_WORKSPACE}/target -s lv1 ${GITHUB_WORKSPACE} 2>&1 | tee autotest.log
          tail -n1 autotest.log | grep -q "PASSED"

      - uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: autotest-lv1-koopa.log
          path: autotest-lv1-koopa.log
  lv1-riscv:
    runs-on: ubuntu-latest
    container:
      image: xecades/compiler-dev
    steps:
      - uses: actions/checkout@v4

      - name: Get rustc version
        run: echo "rustc-version=$(rustc --version)" >> "${GITHUB_OUTPUT}"
        id: get-version

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.get-version.outputs.rustc-version }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Level 1 test
        run: |
          autotest -riscv -w ${GITHUB_WORKSPACE}/target -s lv1 ${GITHUB_WORKSPACE} 2>&1 | tee autotest.log
          tail -n1 autotest.log | grep -q "PASSED"

      - uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: autotest-lv1-riscv.log
          path: autotest-lv1-riscv.log
