name: CI
on:
  push:
    branches: [main]
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        target: [koopa, riscv]
        level: [lv1, lv4, lv3]
        exclude:
          - target: riscv
            level: lv3
          - target: riscv
            level: lv4
    container:
      image: ghcr.io/master-hash/compiler-dev
    steps:
      - uses: actions/checkout@v4

      - name: Get rustc version
        run: echo "rustc-version=$(rustc --version)" >> "${GITHUB_OUTPUT}"
        id: get-version

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.get-version.outputs.rustc-version }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Level ${{ matrix.level }} ${{ matrix.target }} test
        run: |
          autotest -${{ matrix.target }} -w ${GITHUB_WORKSPACE}/target -s ${{ matrix.level }} ${GITHUB_WORKSPACE} 2>&1 | tee autotest.log
          tail -n1 autotest.log | grep -q "PASSED"

      - uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: autotest-${{ matrix.level }}-${{ matrix.target }}.log
          path: autotest.log
